Django 3.0 does not like regional language codes
Having these breaks "makemigrations" when trying to upgrade from
Django 2.2 to 3.0, no idea why yet. For now just working around this.

Error I was getting:

  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/translation.py", line 43, in <listcomp>
    for tag, _ in settings.LANGUAGES if not isinstance(tag, str) # or not language_code_re.match(tag)
  ValueError: too many values to unpack (expected 2)